## Options to make tmux more pleasant

# No mouse
set -g mouse off

# Better colours
set -g default-terminal "tmux-256color"

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Remove delay when switching between panes
set-option -g repeat-time 0

# Increase history buffer
set-option -g history-limit 100000

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Activity monitoring
setw -g monitor-activity off

# Show Activity on message
set -g visual-activity off

# Don't panic
set-option -g bell-action none

# Bind to Ctrl-Space
unbind C-b
set -g prefix C-Space

# qe window traversal
bind -n M-q previous-window
bind -n M-e next-window

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# set window split
bind-key v split-window -h -c "#{pane_current_path}"
bind-key h split-window -c "#{pane_current_path}"

## Appearance

# Default colours
set-option -g status-style default
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow

set -g status-interval 1
set -g status-right-length 140

# Left
set -g status-left-length 20
set -g status-left '#[fg=colour232,bg=colour203] #S #[fg=colour203,bg=default]'

# Center
set -g status-justify centre # center align window list
set-window-option -g window-status-style fg=colour244,bg=default,dim
set-window-option -g window-status-format '#[fg=colour255,bg=colour239] #I #[fg=colour250,bg=colour237] #{pane_current_command} #(pwd="#{pane_current_path}"; echo ${pwd####*/}) #F '

set-window-option -g window-status-current-style fg=colour1,bg=colour0,bright
set-window-option -g window-status-current-format '#[fg=colour233,bg=colour11] #I #[fg=colour233,bg=colour3] #{pane_current_command} #(pwd="#{pane_current_path}";echo ${pwd####*/}) '

# Right
set -g status-right '#[fg=colour111,bg=colour233]#[fg=colour233,bg=colour111] %Y-%m-%d #[fg=colour233,bg=colour105] %a #[fg=colour233,bg=colour99] %H:%M:%S '

# pane border
set-option -g pane-border-style fg=magenta
set-option -g pane-active-border-style fg=colour240
